# 운영용 데이터베이스 설정 (환경변수)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1         # 유휴 커넥션 최소 수
      maximum-pool-size: 10   # 최대 커넥션 수
      idle-timeout: 30000     # 커넥션 유휴 시간 (ms)
      max-lifetime: 1800000   # 커넥션 최대 수명 (ms)
      connection-timeout: 30000 # 커넥션 획득 대기 시간 (ms)
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# 운영용 포트 (환경변수)
server:
  port: ${SERVER_PORT:8080}

# 운영용 로깅 레벨
logging:
  level:
    root: INFO
    com.kopo_team4.hanabank_backend: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

# 운영용 Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    url: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: false
    doc-expansion: none
  show-actuator: true
